services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: booky_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
