services:
  booky_api_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: booky_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - booky_api_app-network
    restart: always

  booky_api_app:
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - booky_api_db
    networks:
      - booky_api_app-network

networks:
  booky_api_app-network:
    driver: bridge
